language: python
python:
- '3.5'
install:
- pip install -r build_requirements.txt
- pip install -r example_django_app/requirements.txt
script:
- python setup.py sdist
- python example_django_app/manage.py test
deploy:
  provider: pypi
  user: __token__
  password:
    secure: drmYGCMP+D4+Shpokv0y3pRs5DxUR1EtUkJAvFbtJL8VMl9o4hSXaBSLytbINJCo9n4oTImxbRTwa3LK4Hgeoh4byAuX0YUunaM95X10Z4m2438kflXjm07bWgc48zrq6Lzk9k5SkC3vbs0NQJ/RkVw3Ppt2sa5Ywi0/ewgEmGuyVbJgFRisAD1NGMYNPIyNWHmgonCc8daN9jAPecJyA/Ty7g4IJfvcu4woM1Oa1HlGjcjTopoBsUMqzkv2ZcaNQWecSnFvG2uiIXTqtZJZN4kEV+k7UMUpbMZY8fK0gjNfeixKh9zV53S6xk6RPJuXxo/f8yWE2wxS1O/CUOmg5VZrwi3yeFhI03GNIner7WdYU0DG8Qe9eHIx2uFPvvfpi+pIRZfL8i/sraMxTTYthTlaBh0mbAJS9m39ltNanvVQtxXB7uPo5rk1J6pqLzgT1Va8LY9oNDQPlwaBsqIM6fzBSmHjz3r/NdSDNpmk7V8/VKVOPqwnEjZ+F1NdrBfWuZDj9DkyGft2l9PCFegO9lRnsC0LgMhlk+8JoP6qaA5sZlZORv5OwPIrZzYv/VZ3IB1ONbYA4RQKqzapp1HaBjdoiRHgxffNN+TqwxKC/SExaemvdeXa2DRv/C7iWAzfoR8kiT3lcKD6sp/YIocRoiI23BqCo2VsDapPREvkgbU=
  on:
    branch: production
